### ISSUE TITLE
Unable to build superset-ui-plugins-deckgl

### ISSUE THREAD

**Issue by kentore82** [apache-superset/superset-ui-plugins-deckgl#7]
**Describe the bug**
Unable to build superset-ui-plugins-deckgl, `Error: Module @superset-ui/build-config defined in "beemo.module" could not be found.`

**To Reproduce**
1. Get latest release from github:
> `wget -O /tmp/v0.1.1.tar.gz https://github.com/apache-superset/superset-ui-plugins-deckgl/archive/v0.1.1.tar.gz && tar xzf /tmp/v0.1.1.tar.gz -C ./`
2. yarn install
```
/tmp/my/superset-ui-plugins-deckgl-0.1.1$ yarn install
yarn install v1.12.3
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @superset-ui/build-config > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning @superset-ui/commit-config > @commitlint/cli > babel-polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @superset-ui/commit-config > @commitlint/cli > babel-polyfill > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > kepler.gl > react-file-drop@0.1.9: Please update to 0.2.2+ for support of the latest react, improved browser support, and typescript definitions
warning workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > @data-ui/event-flow > @babel/runtime-corejs2 > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > react-palm > react-reconciler > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > kepler.gl > react-vis > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > storybook-addon-jsx > @storybook/components > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > storybook-addon-jsx > @storybook/components > react-popper-tooltip > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
[3/5] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-deckgl > react-bootstrap-slider@2.1.5" has unmet peer dependency "bootstrap@^3.3.7".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > react-palm@3.1.2" has unmet peer dependency "enzyme@^3.6.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > react-palm@3.1.2" has unmet peer dependency "enzyme-adapter-utils@^1.8.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > react-palm@3.1.2" has unmet peer dependency "react-test-renderer@^16.4.1".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > kepler.gl > react-palm@2.0.0" has unmet peer dependency "enzyme@^3.6.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > kepler.gl > react-palm@2.0.0" has unmet peer dependency "enzyme-adapter-utils@^1.8.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > kepler.gl > react-palm@2.0.0" has unmet peer dependency "react-test-renderer@^16.4.1".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > terser-webpack-plugin@2.3.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > @data-ui/event-flow@0.0.80" has unmet peer dependency "aphrodite@^1.2.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > kepler.gl > react-tooltip@3.11.4" has incorrect peer dependency "react@>=^16.0.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/legacy-preset-chart-kepler > kepler.gl > react-tooltip@3.11.4" has incorrect peer dependency "react-dom@>=^16.0.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > @storybook/addons > @storybook/api@5.3.10" has unmet peer dependency "regenerator-runtime@*".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > @data-ui/event-flow > recompose@0.23.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-d2c40cee-6886-43a5-a632-aaa723bc6dcc > @superset-ui/plugins-demo > @storybook/addon-actions > react-inspector > storybook-chromatic@2.2.2" has unmet peer dependency "@storybook/core@3.* || 4.* || 5.*".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 64.07s.
```
4. yarn build
```
/tmp/my/superset-ui-plugins-deckgl-0.1.1$ yarn build
yarn run v1.12.3
$ yarn build:cjs && yarn build:esm && yarn run type:dts && yarn build:assets
$ NODE_ENV=production beemo babel --extensions=".js,.jsx,.ts,.tsx" ./src --out-dir lib/ --delete-dir-on-start --minify --workspaces="@superset-ui/!(plugins-demo)"
beemo babel

Transpile files with Babel

Options:
  --version      Show version number                                   [boolean]
  --config       Path to a configuration file             [string] [default: ""]
  --debug        Show debug messages                  [boolean] [default: false]
  --locale       Locale to display output in              [string] [default: ""]
  --output       Control output size (1-3)                 [number] [default: 3]
  --silent       Hide all output                      [boolean] [default: false]
  --theme        Change output colors              [string] [default: "default"]
  --help         Show help                                             [boolean]
  --clean        Clean the target folder              [boolean] [default: false]
  --concurrency  Number of builds to run in parallel       [number] [default: 0]
  --graph        Prioritize workspace builds based on dependency graph
                                                       [boolean] [default: true]
  --stdio        Customize how output is displayed
           [string] [choices: "buffer", "stream", "inherit"] [default: "buffer"]
  --workspaces   Run command in each workspace (supports regex)
                                                          [string] [default: ""]

Error: Module @superset-ui/build-config defined in "beemo.module" could not be found.
    at Beemo.getConfigModuleRoot (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/core/lib/Beemo.js:193:19)
    at Beemo.prepareContext (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/core/lib/Beemo.js:274:35)
    at Beemo.runDriver (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/core/lib/Beemo.js:204:30)
    at Object.app.command.args [as handler] (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/cli/lib/CLI.js:54:22)
    at Object.runCommand (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/cli/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/cli/node_modules/yargs/yargs.js:1107:41)
    at Object.get [as argv] (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/cli/node_modules/yargs/yargs.js:1041:21)
    at Object.<anonymous> (/tmp/my/superset-ui-plugins-deckgl-0.1.1/node_modules/@beemo/cli/lib/CLI.js:125:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Successful build.

**Environment (please complete the following information):**
 - superset-ui-plugins-deckgl version: v0.1.1
 - Node version: `v10.15.3`
 - npm version: `6.13.4`
 - yarn version: `1.12.3` 
 
**Additional context**
`@superset-ui/build-config` is present in `./node_modules`

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
